### ISSUE TITLE
Custom css style

### ISSUE THREAD

**Issue by dtelaroli** [bdparrish/cytoscape.js-toolbar#5]
I need custom css style to improve layout.

**Comment by bdparrish** [comment]
If you take a look at the demo and options available, then you can see where to define a custom css class for both the toolbar and toolbar-items in order to know the CSS selector to use.  You can use the default selectors: `.ui-cytoscape-toolbar` & `.tool-item-list` respectively for toolbar and toolbar-items.

**Comment by dtelaroli** [comment]
The API add inline style, I would like change it.
But ok. I will fork the project.

**Comment by bdparrish** [comment]
Why you couldn't use the '!important' for this.
