### ISSUE TITLE
Is it possible to add event listener when a user click the icon of the toolbar?

### ISSUE THREAD

**Issue by hongjiedai** [bdparrish/cytoscape.js-toolbar#7]
As I learned from the demo, the event binds to cy, node and edge.
Is it possible to fire an event when a user click the icon?

For example, zoom in the canvas by directly click the "zoom in" icon instead of click the canvas?

Thank you.

**Comment by bdparrish** [comment]
Cytoscape uses gestures and events on certain items to do this in order to be made available on all devices including touch devices.  You can override action bindings to buttons by using button id attributes if you would like in the onReady() event.  I am always happy to take a look at PRs for changes.
